const mongoose = require("mongoose");
const Schema = mongoose.Schema;

const eventSchema = new Schema({
  // event_id is nothing but the _id generated by mongodb
  gameName: {
    type: String,
    required: true,
  },
  time: {
    type: String,
    required: true,
  },
  venue: {
    type: String,
    required: true,
  },
  student_info: [
    {
      name: {
        type: String,
        required: true,
      },
    },
  ],
  finish: {
    type: Boolean,
    required: true,
  },
  winner: {
    type: String,
  },
  // number_players: {
  //   type: Number,
  // },
  // date: {
  //   type: String,
  //   required: true,
  // },
  // gender: {
  //   type: String,
  //   required: true,
  // },
});

const Event = mongoose.model("events", eventSchema);

module.exports = Event;
